name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - master

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Navigate to the React app directory and install dependencies
      - name: Install Dependencies
        run: |
          npm install

      # Step 3: Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install --global vercel

      # Step 4: Pull Vercel Environment Information
      - name: Pull Vercel Environment Information
        run: |
          cd react-app
          vercel pull --yes --environment=production --token=${{secrets.VERCEL_TOKEN}}

      # Step 5: Build the Project Artifacts
      - name: Build the Project Artifacts
        run: |
          cd react-app
          vercel build --prod --token=${{secrets.VERCEL_TOKEN}}

      # Step 6: Deploy Project Artifacts
      - name: Deploy Project Artifacts
        run: |
          cd react-app
          vercel deploy --prebuilt --prod --token=${{secrets.VERCEL_TOKEN}}
